import FWCore.ParameterSet.Config as cms

process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonClustersRefRemoval_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonMaskedMeasurementTrackerEvent_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonPixelLayerPairs_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonTrackingRegions_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonPixelClusterCheck_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonPixelHitDoublets_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonPixelSeeds_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonCkfTrackCandidates_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonCtfWithMaterialTracks_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonTrackCutClassifier_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonTrackSelectionHighPurity_cfi')

HLTIterativeTrackingIteration3ForIterL3FromL1Muon = cms.Sequence(process.hltIter3IterL3FromL1MuonClustersRefRemoval+process.hltIter3IterL3FromL1MuonMaskedMeasurementTrackerEvent+process.hltIter3IterL3FromL1MuonPixelLayerPairs+process.hltIter3IterL3FromL1MuonTrackingRegions+process.hltIter3IterL3FromL1MuonPixelClusterCheck+process.hltIter3IterL3FromL1MuonPixelHitDoublets+process.hltIter3IterL3FromL1MuonPixelSeeds+process.hltIter3IterL3FromL1MuonCkfTrackCandidates+process.hltIter3IterL3FromL1MuonCtfWithMaterialTracks+process.hltIter3IterL3FromL1MuonTrackCutClassifier+process.hltIter3IterL3FromL1MuonTrackSelectionHighPurity)
