import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTIterL3MuonRecoPixelTracksSequence_cff import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelVertices_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonTrimmedPixelVertices_cfi import *

HLTIterL3MuonRecopixelvertexingSequence = cms.Sequence(HLTIterL3MuonRecoPixelTracksSequence+hltIterL3MuonPixelVertices+hltIterL3MuonTrimmedPixelVertices)
