import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonClustersRefRemoval_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonMaskedMeasurementTrackerEvent_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonPixelLayerTriplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonPixelClusterCheck_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonPixelHitDoublets_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonPixelHitTriplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonPixelSeeds_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonCkfTrackCandidates_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonCtfWithMaterialTracks_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonTrackCutClassifier_cfi import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonTrackSelectionHighPurity_cfi import *

HLTIterativeTrackingIteration2ForIterL3Muon = cms.Sequence(hltIter2IterL3MuonClustersRefRemoval+hltIter2IterL3MuonMaskedMeasurementTrackerEvent+hltIter2IterL3MuonPixelLayerTriplets+hltIter2IterL3MuonPixelClusterCheck+hltIter2IterL3MuonPixelHitDoublets+hltIter2IterL3MuonPixelHitTriplets+hltIter2IterL3MuonPixelSeeds+hltIter2IterL3MuonCkfTrackCandidates+hltIter2IterL3MuonCtfWithMaterialTracks+hltIter2IterL3MuonTrackCutClassifier+hltIter2IterL3MuonTrackSelectionHighPurity)
