import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration0ForIterL3FromL1Muon_cff import *
from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration2ForIterL3FromL1Muon_cff import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3FromL1MuonMerged_cfi import *
from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration3ForIterL3FromL1Muon_cff import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3FromL1MuonMerged_cfi import *

HLTIterativeTrackingIter023ForIterL3FromL1Muon = cms.Sequence(HLTIterativeTrackingIteration0ForIterL3FromL1Muon+HLTIterativeTrackingIteration2ForIterL3FromL1Muon+hltIter2IterL3FromL1MuonMerged+HLTIterativeTrackingIteration3ForIterL3FromL1Muon+hltIter3IterL3FromL1MuonMerged)
