import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonClustersRefRemoval_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonMaskedMeasurementTrackerEvent_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonPixelLayerPairs_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonL2Candidates_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonTrackingRegions_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonPixelClusterCheck_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonPixelHitDoublets_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonPixelSeeds_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonCkfTrackCandidates_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonCtfWithMaterialTracks_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonTrackCutClassifier_cfi import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonTrackSelectionHighPurity_cfi import *

HLTIterativeTrackingIteration3ForIterL3Muon = cms.Sequence(hltIter3IterL3MuonClustersRefRemoval+hltIter3IterL3MuonMaskedMeasurementTrackerEvent+hltIter3IterL3MuonPixelLayerPairs+hltIter3IterL3MuonL2Candidates+hltIter3IterL3MuonTrackingRegions+hltIter3IterL3MuonPixelClusterCheck+hltIter3IterL3MuonPixelHitDoublets+hltIter3IterL3MuonPixelSeeds+hltIter3IterL3MuonCkfTrackCandidates+hltIter3IterL3MuonCtfWithMaterialTracks+hltIter3IterL3MuonTrackCutClassifier+hltIter3IterL3MuonTrackSelectionHighPurity)
