import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration0ForIterL3Muon_cff import *
from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration2ForIterL3Muon_cff import *
from HLTrigger.PhaseII.Producers.hltIter2IterL3MuonMerged_cfi import *
from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIteration3ForIterL3Muon_cff import *
from HLTrigger.PhaseII.Producers.hltIter3IterL3MuonMerged_cfi import *

HLTIterativeTrackingIter023ForIterL3Muon = cms.Sequence(HLTIterativeTrackingIteration0ForIterL3Muon+HLTIterativeTrackingIteration2ForIterL3Muon+hltIter2IterL3MuonMerged+HLTIterativeTrackingIteration3ForIterL3Muon+hltIter3IterL3MuonMerged)
