import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracksFilter_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracksFitter_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracksTrackingRegions_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelLayerQuadruplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracksHitDoublets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracksHitQuadruplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3MuonPixelTracks_cfi import *

HLTIterL3MuonRecoPixelTracksSequence = cms.Sequence(hltIterL3MuonPixelTracksFilter+hltIterL3MuonPixelTracksFitter+hltIterL3MuonPixelTracksTrackingRegions+hltIterL3MuonPixelLayerQuadruplets+hltIterL3MuonPixelTracksHitDoublets+hltIterL3MuonPixelTracksHitQuadruplets+hltIterL3MuonPixelTracks)
