import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTRecopixelvertexingSequenceForIterL3FromL1Muon_cff import *
from HLTrigger.PhaseII.Sequences.HLTIterativeTrackingIter023ForIterL3FromL1Muon_cff import *

HLTIterL3IOmuonFromL1TkCandidateSequence = cms.Sequence(HLTRecopixelvertexingSequenceForIterL3FromL1Muon+HLTIterativeTrackingIter023ForIterL3FromL1Muon)
