import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTDoLocalPixelSequence_cff import *
from HLTrigger.PhaseII.Sequences.HLTDoLocalStripSequence_cff import *
from HLTrigger.PhaseII.Sequences.HLTIterL3OIAndIOFromL2muonTkCandidateSequence_cff import *
from HLTrigger.PhaseII.Producers.hltL1MuonsPt0_cfi import *
from HLTrigger.PhaseII.Sequences.HLTIterL3IOmuonFromL1TkCandidateSequence_cff import *

HLTIterL3muonTkCandidateSequence = cms.Sequence(HLTDoLocalPixelSequence+HLTDoLocalStripSequence+HLTIterL3OIAndIOFromL2muonTkCandidateSequence+hltL1MuonsPt0+HLTIterL3IOmuonFromL1TkCandidateSequence)
