import FWCore.ParameterSet.Config as cms

process.load('HLTrigger.PhaseII.Sequences.HLTRecoPixelTracksSequenceForIterL3FromL1Muon_cff')
process.load('HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelVertices_cfi')
process.load('HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonTrimmedPixelVertices_cfi')

HLTRecopixelvertexingSequenceForIterL3FromL1Muon = cms.Sequence(process.HLTRecoPixelTracksSequenceForIterL3FromL1Muon+process.hltIterL3FromL1MuonPixelVertices+process.hltIterL3FromL1MuonTrimmedPixelVertices)
