import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelTracksTrackingRegions_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelLayerQuadruplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelTracksHitDoublets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelTracksHitQuadruplets_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelTracks_cfi import *

HLTRecoPixelTracksSequenceForIterL3FromL1Muon = cms.Sequence(hltIterL3FromL1MuonPixelTracksTrackingRegions+hltIterL3FromL1MuonPixelLayerQuadruplets+hltIterL3FromL1MuonPixelTracksHitDoublets+hltIterL3FromL1MuonPixelTracksHitQuadruplets+hltIterL3FromL1MuonPixelTracks)
