import FWCore.ParameterSet.Config as cms

from HLTrigger.PhaseII.Sequences.HLTRecoPixelTracksSequenceForIterL3FromL1Muon_cff import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonPixelVertices_cfi import *
from HLTrigger.PhaseII.Producers.hltIterL3FromL1MuonTrimmedPixelVertices_cfi import *

HLTRecopixelvertexingSequenceForIterL3FromL1Muon = cms.Sequence(HLTRecoPixelTracksSequenceForIterL3FromL1Muon+hltIterL3FromL1MuonPixelVertices+hltIterL3FromL1MuonTrimmedPixelVertices)
